### ISSUE TITLE
[Review] 1week assignment

### ISSUE THREAD

**Issue by unanchoi** [LikeLion-at-CAU-10th/Sangmin-Lee#1]
### 😀 잘한점
- 세션 때 다뤘던 html 태그들을 적절하게 사용해주셨습니다!
- 세션 때 다룬 내용 외의 css내용들을 잘 숙지하셔서 적용해주신 것 같습니다.

### 😌 보완점
- card.html에서 img태그와 h1 태그에 있는 style을 card.css에 지정해주시면 좋을 것 같아요!
- h1 태그는 이미 font size와 font-weight가 지정되어 있는 태그이므로, p태그 혹은 div 태그를 사용하셔서, 스타일을 지정해주시면 좋을 것 같아요!
- card.css 
```CSS

.out_box {
  border: 2px solid black;
  width: 30%;
  text-align: center;
  padding: 30px;
  height: 400px;
  border-radius: 20px;
  margin: auto;
  padding-left: 0;
  padding-right: 0;
  background-color: aquamarine;
}
```
padding 을 none으로 지정하시고, 아래 padding-left, right를 다시 지정 하셨는데 이부분 수정되면 좋을 것 같습니다.
- introduce.html 에서 dev 태그는 오타인건지, 일부러 그렇게 넣어두신건지 궁금합니다!
- font style을 주기 위해서 class를 지정하기 보다는, class에 다른 네이밍을 주신후에 style을 주시는게 더 좋은 것 같습니다!
